sigmasq.out : No1/calcsigmasq.c No1/mainsigmasq.c 
	gcc -o sigmasq.out No1/calcsigmasq.c No1/mainsigmasq.c

pai1overksq.out : No2/calcpai1overksq.c  No2/mainpai1overksq.c 
	gcc -o pai1overksq.out No2/calcpai1overksq.c  No2/mainpai1overksq.c 

factorial.out : No3/calcfactorial.c  No3/mainfactorial.c
	gcc -o factorial.out No3/calcfactorial.c  No3/mainfactorial.c

nCm.out : No4/calcnCm.c  No4/mainnCm.c  
	gcc -o nCm.out No4/calcnCm.c  No4/mainnCm.c  





